In [10]:
import numpy as np

X = np.array (([2, 9], [1, 5], [3, 6]), dtype = float)
y = np.array (([92],[86],[89]), dtype = float)
X = X / np.amax (X, axis = 0)
y = y / 100

In [22]:
def sigmoid (x):
    return 1 / (1 + np.exp (-x))
def der_sig (x):
    return x * (1 - x)

In [23]:
epoch = 5
input_neurons = 2
hidden_neurons = 3
output_neurons = 1

lr = 0.1

wh = np.random.uniform (size = (input_neurons, hidden_neurons))
bh = np.random.uniform (size = (1, hidden_neurons))
wout = np.random.uniform (size = (hidden_neurons, output_neurons))
bout = np.random.uniform (size = (1, output_neurons))

In [24]:
for i in range (5):
    hinp1 = np.dot (X, wh)
    hinp = hinp1 + bh
    hlayer_act = sigmoid (hinp)
    
    outin1 = np.dot (hlayer_act, wout)
    outin = outin1 + bout
    output = sigmoid (outin)
    
    EO = y - output
    outgrad = der_sig (output)
    d_output = EO * outgrad
    
    EH = d_output.dot(wout.T)
    hiddengrad = der_sig (hlayer_act)
    d_hidden = EH * hiddengrad
    
    wout += hlayer_act.T.dot(d_output) * lr
    wh += X.T.dot(d_hidden) * lr
    
    print ("-----------Epoch-", i+1, "Starts----------")
    print("Input: \n" + str(X)) 
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" ,output)
    print ("-----------Epoch-", i+1, "Ends----------\n")

print ("input : ", X)
print ("output : ", y)
print ("predicted output : ", output)

-----------Epoch- 1 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.85766876]
 [0.84343053]
 [0.85636323]]
-----------Epoch- 1 Ends----------

-----------Epoch- 2 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.85799284]
 [0.84374947]
 [0.85668328]]
-----------Epoch- 2 Ends----------

-----------Epoch- 3 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.858313  ]
 [0.84406462]
 [0.85699947]]
-----------Epoch- 3 Ends----------

-----------Epoch- 4 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.85862931]
 [0.84437604]
 [0.857

## Practice 2

In [39]:
import numpy

x = np.array (([1, 2], [5, 8], [10, 12]), dtype = float)
y = np.array (([92], [86], [89]), dtype = float)
x = x / np.amax (x, axis = 0)
y = y/100

def sigmoid (x):
    return 1 / (1 + np.exp (-x))
def der_sig (x):
    return x * (1 - x)

epooch = 100
lr  = 0.1

input_units = 2
output_units = 1
hidden_units = 3

wh = np.random.uniform (size = (input_units, hidden_units))
bh = np.random.uniform (size = (1, hidden_units))

wout = np.random.uniform (size = (hidden_units, output_units))
bout = np.random.uniform (size = (1, output_units))

for i in range (100000):
    hinp1 = np.dot (x, wh)
    hinp = hinp1 + bh
    hlayer_act = sigmoid (hinp)
    
    outin1 = np.dot (hinp, wout)
    outin = outin1 + bout
    output = sigmoid (outin)
    
    EO = y - output
    outgrad = der_sig (output)
    d_output = EO * outgrad
    
    EH = d_output.dot (wout.T)
    hiddengrad = der_sig (hlayer_act)
    d_hidden = EH * hiddengrad
    
    wout += hlayer_act.T.dot (d_output) * lr
    wh += x.T.dot (d_hidden) * lr
    
#     print ("epoch ", i, " start \n")
    
#     print ("input : \n", str (x))
#     print ("output : \n", str (y))
#     print ("predictions : \n", str(output))
    
#     print ("epoch ", i, " end\n") 
    
#     print ("********************************")

print ("input : ", x)
print ("output : ", y)
print ("predictions : ", output)

input :  [[0.1        0.16666667]
 [0.5        0.66666667]
 [1.         1.        ]]
output :  [[0.92]
 [0.86]
 [0.89]]
predictions :  [[0.91155893]
 [0.87312513]
 [0.88253753]]
